(function(){var h={},mt={},c={id:"1c7cd3c160ce650a5dfbf16d8f8d7143",dm:["beifeng.com","pht.zoosnet.net"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:false,align:-1,nv:1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:7448201,qiao:0,lxb:7448201,kbtrk:0,pt:0,spa:0,aet:'',hca:'893A5346B340BA38',conv:0,med:0,cvcc:{id:/hz6d/i,q:/kefu|53kf|openkf/i},cvcf:[],apps:''};var s=void 0,u=!0,w=null,x=!1;mt.cookie={};mt.cookie.set=function(a,e,b){var d;b.O&&(d=new Date,d.setTime(d.getTime()+b.O));document.cookie=a+"="+e+(b.domain?"; domain="+b.domain:"")+(b.path?"; path="+b.path:"")+(d?"; expires="+d.toGMTString():"")+(b.sc?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:w};
mt.cookie.Qb=function(a,e){try{var b="Hm_ck_"+ +new Date;mt.cookie.set(b,"is-cookie-enabled",{domain:a,path:e,O:s});var d="is-cookie-enabled"===mt.cookie.get(b)?"1":"0";mt.cookie.set(b,"",{domain:a,path:e,O:-1});return d}catch(f){return"0"}};mt.lang={};mt.lang.d=function(a,e){return"[object "+e+"]"==={}.toString.call(a)};mt.lang.wa=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.K=function(a){return mt.lang.d(a,"String")};mt.lang.isArray=function(a){return mt.lang.d(a,"Array")};
mt.lang.g=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.lang.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};mt.lang.J=function(a,e){var b=x;if(a==w||!mt.lang.d(a,"Array")||e===s)return b;if(Array.prototype.indexOf)b=-1!==a.indexOf(e);else for(var d=0;d<a.length;d++)if(a[d]===e){b=u;break}return b};mt.url={};mt.url.m=function(a,e){var b=a.match(RegExp("(^|&|\\?|#)("+e+")=([^&#]*)(&|$|#)",""));return b?b[3]:w};
mt.url.pc=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:w};mt.url.wb=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):w};mt.url.Q=function(a){return(a=mt.url.wb(a))?a.replace(/:\d+$/,""):a};mt.url.sa=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):w};
(function(){var a=mt.lang,e=mt.url;mt.f={};mt.f.pa=function(b){return document.getElementById(b)};mt.f.La=function(b){if(!b)return w;try{b=String(b);if(0===b.indexOf("!HMCQ!"))return b;if(0===b.indexOf("!HMCC!"))return document.querySelector(b.substring(6,b.length));for(var d=b.split(">"),a=document.body,e=d.length-1;0<=e;e--)if(-1<d[e].indexOf("#")){var g=d[e].split("#")[1];(a=document.getElementById(g))||(a=document.getElementById(decodeURIComponent(g)));d=d.splice(e+1,d.length-(e+1));break}for(b=
0;a&&b<d.length;){var m=String(d[b]).toLowerCase();if(!("html"===m||"body"===m)){var e=0,p=d[b].match(/\[(\d+)\]/i),g=[];if(p)e=p[1]-1,m=m.split("[")[0];else if(1!==a.childNodes.length){for(var r=0,t=0,q=a.childNodes.length;t<q;t++){var v=a.childNodes[t];1===v.nodeType&&v.nodeName.toLowerCase()===m&&r++;if(1<r)return w}if(1!==r)return w}for(r=0;r<a.childNodes.length;r++)1===a.childNodes[r].nodeType&&a.childNodes[r].nodeName.toLowerCase()===m&&g.push(a.childNodes[r]);if(!g[e])return w;a=g[e]}b++}return a}catch(k){return w}};
mt.f.sa=function(b,d){var a=[],e=[];if(!b)return e;for(;b.parentNode!=w;){for(var g=0,m=0,p=b.parentNode.childNodes.length,r=0;r<p;r++){var t=b.parentNode.childNodes[r];if(t.nodeName===b.nodeName&&(g++,t===b&&(m=g),0<m&&1<g))break}if((p=""!==b.id)&&d){a.unshift("#"+encodeURIComponent(b.id));break}else p&&(p="#"+encodeURIComponent(b.id),p=0<a.length?p+">"+a.join(">"):p,e.push(p)),a.unshift(encodeURIComponent(String(b.nodeName).toLowerCase())+(1<g?"["+m+"]":""));b=b.parentNode}e.push(a.join(">"));return e};
mt.f.Ab=function(b){return(b=mt.f.sa(b,u))&&b.length?String(b[0]):""};mt.f.zb=function(b){return mt.f.sa(b,x)};mt.f.nc=function(b,d){for(d=d.toUpperCase();(b=b.parentNode)&&1==b.nodeType;)if(b.tagName==d)return b;return w};mt.f.tb=function(b){return 9===b.nodeType?b:b.ownerDocument||b.document};mt.f.oc=function(b){var d={top:0,left:0};if(!b)return d;var a=mt.f.tb(b).documentElement;"undefined"!==typeof b.getBoundingClientRect&&(d=b.getBoundingClientRect());return{top:d.top+(window.pageYOffset||a.scrollTop)-
(a.clientTop||0),left:d.left+(window.pageXOffset||a.scrollLeft)-(a.clientLeft||0)}};mt.f.getAttribute=function(a,d){var e=a.getAttribute&&a.getAttribute(d)||w;if(!e&&a.attributes&&a.attributes.length)for(var l=a.attributes,g=l.length,m=0;m<g;m++)l[m].nodeName===d&&(e=l[m].nodeValue);return e};mt.f.Y=function(a){var d="document";a.tagName!==s&&(d=a.tagName);return d.toLowerCase()};mt.f.Db=function(b){var d="";b.textContent?d=a.trim(b.textContent):b.innerText&&(d=a.trim(b.innerText));d&&(d=d.replace(/\s+/g,
" ").substring(0,255));return d};mt.f.qa=function(b,d){var f;a.K(b)&&0===String(b).indexOf("!HMCQ!")?(f=String(b),f=e.m(document.location.href,f.substring(6,f.length))):a.K(b)||(f=mt.f.Y(b),"input"===f&&d&&("button"===b.type||"submit"===b.type)?f=a.trim(b.value)||"":"input"===f&&!d&&"password"!==b.type?f=a.trim(b.value)||"":"img"===f?(f=mt.f.getAttribute,f=f(b,"alt")||f(b,"title")||f(b,"src")):f="body"===f||"html"===f?["(hm-default-content-for-",f,")"].join(""):mt.f.Db(b));return String(f||"").substring(0,
255)};(function(){(mt.f.Ba=function(){function a(){if(!a.aa){a.aa=u;for(var d=0,e=l.length;d<e;d++)l[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(d,1);return}a()}var e=x,l=[],g;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,x);a()}:document.attachEvent&&(g=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",g),a())});(function(){if(!e)if(e=u,"complete"===document.readyState)a.aa=u;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",g,x),window.addEventListener("load",a,x);else if(document.attachEvent){document.attachEvent("onreadystatechange",g);window.attachEvent("onload",a);var m=x;try{m=window.frameElement==w}catch(p){}document.documentElement.doScroll&&m&&d()}})();return function(d){a.aa?d():l.push(d)}}()).aa=x})();return mt.f})();mt.event={};
mt.event.e=function(a,e,b){a.attachEvent?a.attachEvent("on"+e,function(d){b.call(a,d)}):a.addEventListener&&a.addEventListener(e,b,x)};mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=x};
(function(){var a=mt.event;mt.h={};mt.h.Qa=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.h.xb=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.h.cookieEnabled=navigator.cookieEnabled;mt.h.javaEnabled=navigator.javaEnabled();mt.h.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.h.Vb=(window.screen.width||0)+"x"+(window.screen.height||0);mt.h.colorDepth=
window.screen.colorDepth||0;mt.h.Z=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.h.R=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.h.orientation=0;(function(){function e(){var a=0;window.orientation!==s&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==s)&&(a=screen.orientation.angle);mt.h.orientation=
a}e();a.e(window,"orientationchange",e)})();return mt.h})();mt.r={};mt.r.parse=function(a){return(new Function("return ("+a+")"))()};
mt.r.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=b[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function e(a){return 10>a?"0"+a:a}var b={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===w)return"null";if(d instanceof Array){var b=["["],l=d.length,g,m,p;for(m=0;m<l;m++)switch(p=d[m],typeof p){case "undefined":case "function":case "unknown":break;default:g&&b.push(","),b.push(mt.r.stringify(p)),g=1}b.push("]");return b.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+e(d.getMonth()+1)+"-"+e(d.getDate())+"T"+e(d.getHours())+":"+e(d.getMinutes())+":"+e(d.getSeconds())+'"';g=["{"];m=mt.r.stringify;for(l in d)if(Object.prototype.hasOwnProperty.call(d,l))switch(p=
d[l],typeof p){case "undefined":case "unknown":case "function":break;default:b&&g.push(","),b=1,g.push(m(l)+":"+m(p))}g.push("}");return g.join("")}}}();mt.localStorage={};mt.localStorage.ga=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(a){return x}return u};
mt.localStorage.set=function(a,e,b){var d=new Date;d.setTime(d.getTime()+b||31536E6);try{window.localStorage?(e=d.getTime()+"|"+e,window.localStorage.setItem(a,e)):mt.localStorage.ga()&&(mt.localStorage.l.expires=d.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(a,e),mt.localStorage.l.save(document.location.hostname))}catch(f){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var e=a.indexOf("|"),b=a.substring(0,e)-0;if(b&&b>(new Date).getTime())return a.substring(e+1)}}else if(mt.localStorage.ga())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(a)}catch(d){}return w};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.ga())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(a),mt.localStorage.l.save(document.location.hostname)}catch(e){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,e){try{window.sessionStorage&&window.sessionStorage.setItem(a,e)}catch(b){}};
mt.sessionStorage.get=function(a){try{return window.sessionStorage?window.sessionStorage.getItem(a):w}catch(e){return w}};mt.sessionStorage.remove=function(a){try{window.sessionStorage&&window.sessionStorage.removeItem(a)}catch(e){}};mt.Ya={};mt.Ya.log=function(a,e){var b=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=b;b.onload=function(){b.onload=w;b=window[d]=w;e&&e(a)};b.src=a};mt.Ca={};
mt.Ca.Eb=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var e=navigator.plugins["Shockwave Flash"];e&&e.description&&(a=e.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(e=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=e.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(b){}return a};
mt.Ca.mc=function(a,e,b,d,f){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+b+'" height="'+d+'"><param name="movie" value="'+e+'" /><param name="flashvars" value="'+(f||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+b+'" height="'+d+'" src="'+e+'" flashvars="'+(f||"")+'" allowscriptaccess="always" /></object>'};
(function(){function a(){for(var a=x,b=document.getElementsByTagName("script"),d=b.length,d=100<d?100:d,f=0;f<d;f++){var l=b[f].src;if(l&&0===l.indexOf("https://hm.baidu.com/h")){a=u;break}}return a}return h.qb=a})();var A=h.qb;
h.o={Lb:"http://tongji.baidu.com/hm-web/welcome/ico",Va:"hm.baidu.com/hm.gif",fb:/^(tongji|hmcdn).baidu.com$/,$a:"tongji.baidu.com",Ib:"hmmd",Jb:"hmpl",gc:"utm_medium",Hb:"hmkw",ic:"utm_term",Fb:"hmci",fc:"utm_content",Kb:"hmsr",hc:"utm_source",Gb:"hmcu",ec:"utm_campaign",L:0,H:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",xa:A()||"https:"===document.location.protocol?"https:":"http:",qc:0,kc:6E5,Rb:6E5,rc:5E3,lc:5,la:1024,jc:1,ca:2147483647,Za:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn p ct u tt hh".split(" "),
S:u,Ia:["a","input","button"],hb:{id:"data-hm-id",ka:"data-hm-class",Fa:"data-hm-xpath",content:"data-hm-content",Da:"data-hm-tag",link:"data-hm-link"},Ha:"data-hm-enabled",Ga:"data-hm-disabled",Sb:"https://hmcdn.baidu.com/static/tongji/plugins/",Ua:["UrlChangeTracker"]};(function(){var a={D:{},e:function(a,b){this.D[a]=this.D[a]||[];this.D[a].push(b)},I:function(a,b){this.D[a]=this.D[a]||[];for(var d=this.D[a].length,f=0;f<d;f++)this.D[a][f](b)}};return h.z=a})();
(function(){function a(a,d){var f=document.createElement("script");f.charset="utf-8";e.d(d,"Function")&&(f.readyState?f.onreadystatechange=function(){if("loaded"===f.readyState||"complete"===f.readyState)f.onreadystatechange=w,d()}:f.onload=function(){d()});f.src=a;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(f,l)}var e=mt.lang;return h.load=a})();
(function(){function a(){var a="";if(h.c.b.nv){a=encodeURIComponent(document.referrer);try{window.sessionStorage?b.set("Hm_from_"+c.id,a):e.set("Hm_from_"+c.id,a,864E5)}catch(f){}}else try{a=(window.sessionStorage?b.get("Hm_from_"+c.id):e.get("Hm_from_"+c.id))||""}catch(l){}return a}var e=mt.localStorage,b=mt.sessionStorage;return h.rb=a})();
(function(){var a=h.o,e={init:function(){if(""!==c.icon){var b=c.icon.split("|"),d=a.Lb+"?s="+c.id,e="https://hmcdn.baidu.com/static"+b[0]+".gif";document.write("swf"===b[1]||"gif"===b[1]?'<a href="'+d+'" target="_blank"><img border="0" src="'+e+'" width="'+b[2]+'" height="'+b[3]+'"></a>':'<a href="'+d+'" target="_blank">'+b[0]+"</a>")}}};h.z.e("pv-b",e.init);return e})();
(function(){var a=mt.cookie,e=mt.localStorage,b=mt.sessionStorage,d={getData:function(d){try{return a.get(d)||b.get(d)||e.get(d)}catch(l){}},setData:function(f,l,g){try{a.set(f,l,{domain:d.P(),path:d.X(),O:g}),g?e.set(f,l,g):b.set(f,l)}catch(m){}},Ub:function(f){try{a.set(f,"",{domain:d.P(),path:d.X(),O:-1}),b.remove(f),e.remove(f)}catch(l){}},T:function(a,d){a="."+a.replace(/:\d+/,"");d="."+d.replace(/:\d+/,"");var b=a.indexOf(d);return-1<b&&b+d.length===a.length},ba:function(a,d){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(d)},P:function(){for(var a=document.location.hostname,b=0,e=c.dm.length;b<e;b++)if(d.T(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},X:function(){for(var a=0,b=c.dm.length;a<b;a++){var e=c.dm[a];if(-1<e.indexOf("/")&&d.ba(document.location.href,e))return e.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.ma=d})();
(function(){var a=mt.lang,e=mt.r,b=h.ma,d={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},f={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},l=["session","user"],g="Hm_up_"+c.id,m={init:function(){m.Ob()},Ob:function(){try{var p=e.parse(decodeURIComponent(b.getData(g)));a.d(p,"Object")&&(d.user=p)}catch(m){}},A:function(a){var b={};d[a]!==s&&(b=d[a]);a=this.ta();for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);return a},ta:function(){for(var a={},b,e=l.length-
1;0<=e;e--){b=d[l[e]];for(var m in b)b.hasOwnProperty(m)&&(a[m]=b[m])}return a},setProperty:function(b,f,g){var q=d[b];if(a.d(q,"Object")&&a.d(f,"Object")){for(var l in f)if(f.hasOwnProperty(l)){var k=a.g(String(l));if(g||!((/^_/.test(k)||/_$/.test(k))&&"_iden"!==k)){var n=f[l];if(n==w)delete q[k];else{if(a.d(n,"Object")||a.d(n,"Array"))n=e.stringify(n);n=a.g(String(n));m.Pb(b,k,n)&&(q[k]={value:n,scope:m.Na(b)})}}}"user"===b&&m.za()}},s:function(b){b!==s&&("userId"===b&&a.d(d.user,"Object")?(delete d.user.uid_,
m.za()):"user"===b&&a.d(d.user,"Object")?(b=d.user.uid_,d.user=b===s?{}:{uid_:b},m.za()):d[b]!==s&&(d[b]={}))},za:function(){try{b.setData(g,encodeURIComponent(e.stringify(d.user)),c.age)}catch(a){}},Pb:function(a,b,e){var f=u,g=d[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(e)).length)f=x;else{var k=g[b];g[b]={value:e,scope:m.Na(a)};a=m.M(m.A(a));2048<encodeURIComponent(a).length&&(k!==s?g[b]=k:delete g[b],f=x)}return f},M:function(a){var b=[],d,e;for(e in a)a.hasOwnProperty(e)&&
(d=[e,a[e].value],(1===a[e].scope||2===a[e].scope)&&d.push(a[e].scope),b.push(d.join("*")));return b.join("!")},Na:function(a){a=f[a];return a!==s?a:f.others}};return h.N=m})();
(function(){var a=mt.f,e=mt.lang,b=mt.r,d=h.z,f=h.N,l=f.M;if(e.isArray(c.cptrk)&&0<c.cptrk.length){var g={Ta:{},ea:{},init:function(){for(var a,d=0;d<c.cptrk.length;d++)try{if(a=b.parse(decodeURIComponent(String(c.cptrk[d]))),a.a!==s&&e.d(a.a,"Object")){var f=a.a,l;for(l in f)f.hasOwnProperty(l)&&(g.ea[l]=String(f[l]))}}catch(q){}},Sa:function(){var d,b,e;for(e in g.ea)if(g.ea.hasOwnProperty(e)&&g.Ta[e]===s&&(d=g.ea[e],d=a.La(d)))b=b===s?{}:b,b[e]=a.qa(d,x),g.Ta[e]=u;return b},ua:function(){var a=
g.Sa();a&&g.Xb(a)},Nb:function(){"MutationObserver"in window?(new MutationObserver(g.ua)).observe(document.body,{childList:u,subtree:u}):window.setInterval(g.ua,15E3)},Xb:function(a){if(e.d(a,"Object")){f.setProperty("pageview",a);a=h.c.b.p;var d=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=l(f.A("pageview"));h.c.i();h.c.b.p=a;h.c.b.ep=d;f.s("pageview")}}};g.init();d.e("pv-b",function(){var a=g.Sa();a&&f.setProperty("pageview",a)});g.Nb();a.Ba(g.ua)}})();
(function(){var a=mt.lang,e=mt.f,b={W:function(a,f){return function(l){var g=l.target||l.srcElement;if(g){var m=g.getAttribute(a.fa);l=l.clientX+":"+l.clientY;if(m&&m===l)g.removeAttribute(a.fa);else if(f&&0<f.length&&(g=e.zb(g))&&g.length)if(m=g.length,l=g[g.length-1],1E4>m*l.split(">").length)for(l=0;l<m;l++)b.Xa(a,g[l]);else b.Xa(a,l)}}},Xa:function(b,e){for(var l={},g=String(e).split(">").length,m=0;m<g;m++)l[e]="",e=e.substring(0,e.lastIndexOf(">"));b&&(a.d(b,"Object")&&b.Ja)&&b.Ja(l)},Tb:function(a,
b){return function(e){(e.target||e.srcElement).setAttribute(a.fa,e.clientX+":"+e.clientY);a&&a.w&&(b?a.w(b):a.w("#"+encodeURIComponent(this.id),e.type))}}};return h.oa=b})();
(function(){var a=mt.f,e=mt.r,b=mt.event,d=mt.lang,f=h.oa,l=h.N,g=l.M,m={fa:"HM_ce",ab:function(){if(c.cetrk&&c.cetrk.length){b.e(document,"click",f.W(m,c.cetrk));for(var d=0,g=c.cetrk.length;d<g;d++){var l;try{l=e.parse(decodeURIComponent(String(c.cetrk[d])))}catch(q){l={}}var v=l.p||"";-1===v.indexOf(">")&&(0===v.indexOf("#")&&(v=v.substring(1)),(v=a.pa(v))&&b.e(v,"click",f.Tb(m,l)))}}},Ja:function(a){if(c.cetrk&&c.cetrk.length)for(var b=0,d=c.cetrk.length;b<d;b++){var f;try{f=e.parse(decodeURIComponent(String(c.cetrk[b])))}catch(g){f=
{}}var k=m.ub(f.p,a);k&&m.w(f,k)}},ub:function(a,b){a=String(a);if(0<a.indexOf("*")){var d=RegExp("^"+a.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),e;for(e in b)if(b.hasOwnProperty(e)&&d.test(e))return e;return w}return b.hasOwnProperty(a)?a:w},w:function(b,e){h.c.b.et=7;var f=b&&b.k||"",f=d.g(f),q={};if(b&&b.a&&d.d(b.a,"Object")){var v=b.a,k;for(k in v)if(v.hasOwnProperty(k)){var n=m.Bb(v[k]||"",e),n=n?a.qa(n,x):"";q[k]=n}}q._iden=f;l.setProperty("customEvent",q);h.c.b.ep=
"";h.c.b.p=g(l.A("customEvent"));h.c.i();h.c.b.p="";l.s("customEvent")},Bb:function(b,d){b=String(b);d=String(d);if(0<b.indexOf("*")){var e=/.*\[(\d+)\]$/.exec(d);b=b.replace("*",e?e[1]:"1")}return a.La(b)}};h.z.e("pv-b",m.ab);return m})();
(function(){var a=mt.lang,e=mt.f,b=mt.event,d=mt.h,f=h.o,l=h.z,g=h.N,m=g.M,p=+new Date,r=[],t={W:function(){return function(b){if(h.c&&h.c.S&&c.aet&&c.aet.length){var d=b.target||b.srcElement;if(d){var k=h.c.Ia,n=e.getAttribute(d,f.Ha)!=w?u:x;if(e.getAttribute(d,f.Ga)==w)if(n)t.ha(t.ra(d,b));else{var z=e.Y(d);if(a.J(k,"*")||a.J(k,z))t.ha(t.ra(d,b));else for(;d.parentNode!=w;){var n=d.parentNode,z=e.Y(n),y="a"===z&&a.J(k,"a")?u:x,z="button"===z&&a.J(k,"button")?u:x,G=e.getAttribute(n,f.Ha)!=w?u:x;
if(e.getAttribute(n,f.Ga)==w&&(y||z||G)){t.ha(t.ra(n,b));break}d=d.parentNode}}}}}},ra:function(b,g){var k={},n=f.hb;k.id=e.getAttribute(b,n.id)||e.getAttribute(b,"id")||"";k.ka=e.getAttribute(b,n.ka)||e.getAttribute(b,"class")||"";k.Fa=e.getAttribute(b,n.Fa)||e.Ab(b);k.content=e.getAttribute(b,n.content)||e.qa(b,u);k.Da=e.getAttribute(b,n.Da)||e.Y(b);k.link=e.getAttribute(b,n.link)||e.getAttribute(b,"href")||"";k.type=g.type||"click";n=a.wa(b.offsetTop)?b.offsetTop:0;"click"===g.type?n=d.Qa?g.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):g.pageY:"touchend"===g.type&&(g.ya&&a.d(g.ya.changedTouches,"Array")&&g.ya.changedTouches.length)&&(n=g.ya.changedTouches[0].pageY);k.dc=n;return k},ha:function(b){var d=a.g;b=[+new Date-(h.c.F!==s?h.c.F:p),d(b.id),d(b.ka),d(b.Da),d(b.Fa),d(b.link),d(b.content),b.type,b.dc].join("*");t.ia(b);a.d(this.V(),"Function")&&this.V()()},ia:function(a){a.length>f.la||(encodeURIComponent(r.join("!")+a).length>f.la&&(t.w(r.join("!")),r=[]),
r.push(a))},w:function(a){h.c.b.et=5;h.c.b.ep=a;h.c.b.p=m(g.A("autoEventTracking"));h.c.i();h.c.b.p=""},V:function(){return function(){r&&r.length&&(t.w(r.join("!")),r=[])}}};a.K(c.aet)&&""!==c.aet&&l.e("pv-b",function(){b.e(document,"click",t.W());"ontouchend"in document&&b.e(window,"touchend",t.W());b.e(window,"unload",t.V())});return t})();
(function(){var a=mt.event,e=mt.h,b=h.o,d=h.z,f=+new Date,l=[],g=w,m={nb:function(){return function(){h.c&&(h.c.S&&c.aet&&c.aet.length)&&(window.clearTimeout(g),g=window.setTimeout(function(){m.cb(e.Z()+e.R())},150))}},cb:function(a){m.ia([+new Date-(h.c.F!==s?h.c.F:f),a].join("*"))},ia:function(a){if(encodeURIComponent(l.join("!")+a).length>b.la||3<l.length)m.w(l.join("!")),l=[];l.push(a)},w:function(a){h.c.b.et=6;h.c.b.vh=e.R();h.c.b.ep=a;h.c.i()},V:function(){return function(){l&&l.length&&(m.w(l.join("!")),
l=[])}}};mt.lang.K(c.aet)&&""!==c.aet&&d.e("pv-b",function(){a.e(window,"scroll",m.nb());a.e(window,"unload",m.V())});return m})();
(function(){var a=mt.f,e=h.o,b=h.load,d=h.rb;h.z.e("pv-b",function(){var f=e.protocol+"//crs.baidu.com/";c.rec&&a.Ba(function(){for(var l=0,g=c.rp.length;l<g;l++){var m=c.rp[l][0],p=c.rp[l][1],r=a.pa("hm_t_"+m);if(p&&!(2==p&&!r||r&&""!==r.innerHTML))r="",r=Math.round(Math.random()*e.ca),r=4==p?f+"hl.js?"+["siteId="+c.id,"planId="+m,"rnd="+r].join("&"):f+"t.js?"+["siteId="+c.id,"planId="+m,"from="+d(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
r].join("&"),b(r)}})})})();
(function(){function a(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.na.yb()+","+h.na.vb();h.c.i()}}function e(){clearTimeout(y);var a;n&&(a="visible"==document[n]);z&&(a=!document[z]);m="undefined"==typeof a?u:a;if((!g||!p)&&m&&r)k=u,q=+new Date;else if(g&&p&&(!m||!r))k=x,v+=+new Date-q;g=m;p=r;y=setTimeout(e,100)}function b(a){var b=document,n="";if(a in b)n=a;else for(var d=["webkit","ms","moz","o"],e=0;e<d.length;e++){var y=d[e]+a.charAt(0).toUpperCase()+a.slice(1);if(y in b){n=
y;break}}return n}function d(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))r="focus"==a.type||"focusin"==a.type?u:x,e()}var f=mt.event,l=h.z,g=u,m=u,p=u,r=u,t=+new Date,q=t,v=0,k=u,n=b("visibilityState"),z=b("hidden"),y;e();(function(){var a=n.replace(/[vV]isibilityState/,"visibilitychange");f.e(document,a,e);f.e(window,"pageshow",e);f.e(window,"pagehide",e);"object"==typeof document.onfocusin?(f.e(document,"focusin",d),f.e(document,"focusout",d)):(f.e(window,"focus",d),
f.e(window,"blur",d))})();h.na={yb:function(){return+new Date-t},vb:function(){return k?+new Date-q+v:v}};l.e("pv-b",function(){f.e(window,"unload",a())});l.e("duration-send",a());l.e("duration-done",function(){q=t=+new Date;v=0});return h.na})();
(function(){var a=mt.lang,e=h.o,b=h.load,d={Mb:function(d){if((window._dxt===s||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.c){var l=h.c.P();b([e.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(l)].join(""),d)}},bc:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.lb=d})();
(function(){function a(a,b,d,e){if(!(a===s||b===s||e===s)){if(""===a)return[b,d,e].join("*");a=String(a).split("!");for(var g,k=x,f=0;f<a.length;f++)if(g=a[f].split("*"),String(b)===g[0]){g[1]=d;g[2]=e;a[f]=g.join("*");k=u;break}k||a.push([b,d,e].join("*"));return a.join("!")}}function e(a){for(var b in a)if({}.hasOwnProperty.call(a,b)){var y=a[b];d.d(y,"Object")||d.d(y,"Array")?e(y):a[b]=String(y)}}var b=mt.url,d=mt.lang,f=mt.r,l=mt.h,g=h.o,m=h.z,p=h.lb,r=h.load,t=h.ma,q=h.N,v=q.M,k={U:[],da:0,Ra:x,
C:{Ea:"",page:""},init:function(){k.j=0;q.init();m.e("pv-b",function(){k.mb();k.ob()});m.e("pv-d",function(){k.pb();k.C.page=""});m.e("stag-b",function(){h.c.b.api=k.j||k.da?k.j+"_"+k.da:"";h.c.b.ct=[decodeURIComponent(t.getData("Hm_ct_"+c.id)||""),k.C.Ea,k.C.page].join("!")});m.e("stag-d",function(){h.c.b.api=0;k.j=0;k.da=0})},mb:function(){var a=window._hmt||[];if(!a||d.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var n=arguments[b];
d.d(n,"Array")&&(a.cmd[a.id].push(n),"_setAccount"===n[0]&&(1<n.length&&/^[0-9a-f]{32}$/.test(n[1]))&&(n=n[1],a.id=n,a.cmd[n]=a.cmd[n]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},ob:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,e=0,g=b.length;e<g;e++){var f=b[e];d.test(f[0])?k.U.push(f):k.Aa(f)}a.cmd[c.id]={push:k.Aa}},pb:function(){if(0<k.U.length)for(var a=0,b=k.U.length;a<b;a++)k.Aa(k.U[a]);k.U=
w},Aa:function(a){var b=a[0];if(k.hasOwnProperty(b)&&d.d(k[b],"Function"))k[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(k.j|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],x===a||u===a))k.j|=2,h.c.Oa=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){k.j|=4;h.c.b.sn=h.c.Ma();h.c.b.et=0;h.c.b.ep="";h.c.b.vl=l.Z()+l.R();h.c.b.kb=0;h.c.va?(h.c.b.nv=0,h.c.b.st=4):h.c.va=u;var b=h.c.b.u,d=h.c.b.su;h.c.b.u=g.protocol+"//"+document.location.host+
a[1];k.Ra||(h.c.b.su=document.location.href);h.c.b.p=v(q.A("pageview"));h.c.i();h.c.b.u=b;h.c.b.su=d;h.c.b.p="";h.c.F=+new Date;q.s("pageview")}},_trackEvent:function(a){2<a.length&&(k.j|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=d.g(a[1])+"*"+d.g(a[2])+(a[3]?"*"+d.g(a[3]):"")+(a[4]?"*"+d.g(a[4]):""),h.c.b.p=v(q.ta()),h.c.i(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],e=a[4]||3;if(0<b&&6>b&&0<e&&4>e){k.da++;for(var g=(h.c.b.cv||"*").split("!"),f=g.length;f<b-1;f++)g.push("*");
g[b-1]=e+"*"+d.g(a[2])+"*"+d.g(a[3]);h.c.b.cv=g.join("!");a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?t.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):t.Ub("Hm_cv_"+c.id)}}},_setUserTag:function(b){if(!(3>b.length)){var e=d.g(b[1]);b=d.g(b[2]);if(e!==s&&b!==s){var y=decodeURIComponent(t.getData("Hm_ct_"+c.id)||""),y=a(y,e,1,b);t.setData("Hm_ct_"+c.id,encodeURIComponent(y),c.age)}}},_setVisitTag:function(b){if(!(3>b.length)){var e=d.g(b[1]);b=d.g(b[2]);if(e!==
s&&b!==s){var y=k.C.Ea,y=a(y,e,2,b);k.C.Ea=y}}},_setPageTag:function(b){if(!(3>b.length)){var e=d.g(b[1]);b=d.g(b[2]);if(e!==s&&b!==s){var y=k.C.page,y=a(y,e,3,b);k.C.page=y}}},_setReferrerOverride:function(a){1<a.length&&(h.c.b.su=a[1].charAt&&"/"===a[1].charAt(0)?g.protocol+"//"+window.location.host+a[1]:a[1],k.Ra=u)},_trackOrder:function(a){a=a[1];d.d(a,"Object")&&(e(a),k.j|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=f.stringify(a),h.c.b.p=v(q.ta()),h.c.i(),h.c.b.p="")},_trackMobConv:function(a){if(a=
{webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])k.j|=32,h.c.b.et=93,h.c.b.ep=a,h.c.i()},_setDataxId:function(a){a=a[1];p.Mb();p.bc(a)},_setUserId:function(a){a=a[1];if(a!==s&&(d.K(a)||d.wa(a))){var b=q.A("user").uid_;if(!(b&&b.value===d.g(String(a)))){var b=h.c.b.p,e=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+d.g(String(a));h.c.i();var g={};g.uid_=a;q.setProperty("user",g,u);h.c.b.p=b;h.c.b.ep=e}}},_clearUserId:function(a){1<a.length&&u===a[1]&&q.s("userId")},_setUserProperty:function(a){a=
a[1];d.d(a,"Object")&&q.setProperty("user",a)},_clearUserProperty:function(a){1<a.length&&u===a[1]&&q.s("user")},_setSessionProperty:function(a){a=a[1];d.d(a,"Object")&&q.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&u===a[1]&&q.s("session")},_setPageviewProperty:function(a){a=a[1];d.d(a,"Object")&&q.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&u===a[1]&&q.s("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];d.d(a,"Object")&&q.setProperty("autoEventTracking",
a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&u===a[1]&&q.s("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],x===a||u===a))h.c.Pa=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],x===a||u===a))h.c.S=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.i())):m.I("duration-send");m.I("duration-done")},_require:function(a){1<a.length&&(a=a[1],g.fb.test(b.Q(a))&&r(a))},_providePlugin:function(a){if(1<
a.length){var b=window._hmt,e=a[1];a=a[2];if(d.J(g.Ua,e)&&d.d(a,"Function")&&(b.plugins=b.plugins||{},b.G=b.G||{},b.plugins[e]=a,b.B=b.B||[],a=b.B.slice(),e&&a.length&&a[0][1]===e))for(var f=0,k=a.length;f<k;f++){var l=a[f][2]||{};if(b.plugins[e]&&!b.G[e])b.G[e]=new b.plugins[e](l),b.B.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1],f=a[2]||{};if(d.J(g.Ua,e))if(b.plugins=b.plugins||{},b.G=b.G||{},b.plugins[e]&&!b.G[e])b.G[e]=new b.plugins[e](f);else{b.B=b.B||
[];for(var f=0,l=b.B.length;f<l;f++)if(b.B[f][1]===e)return;b.B.push(a);k._require([w,g.Sb+e+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];d.d(a,"Object")||(a={});a._iden=b;q.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=v(q.A("customEvent"));h.c.i();h.c.b.p="";q.s("customEvent")}}};k.init();h.gb=k;return h.gb})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=u,this.b={},this.Pa=this.Oa=u,this.S=k.S,this.Ia=f.K(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.va=x,this.init())}var e=mt.url,b=mt.Ya,d=mt.Ca,f=mt.lang,l=mt.cookie,g=mt.h,m=mt.sessionStorage,p=mt.r,r=mt.event,t=h.ma,q=h.N,v=q.M,k=h.o,n=h.load,z=h.z;a.prototype={T:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var e=a.indexOf(b);return-1<e&&e+b.length===a.length},ba:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},$:function(a){for(var b=0;b<c.dm.length;b++)if(-1<c.dm[b].indexOf("/")){if(this.ba(a,c.dm[b]))return u}else{var d=e.Q(a);if(d&&this.T(d,c.dm[b]))return u}return x},P:function(){for(var a=document.location.hostname,b=0,e=c.dm.length;b<e;b++)if(this.T(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},X:function(){for(var a=0,b=c.dm.length;a<b;a++){var e=c.dm[a];if(-1<e.indexOf("/")&&this.ba(document.location.href,e))return e.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},Cb:function(){if(!document.referrer)return k.H-k.L>c.vdur?1:4;var a=x;this.$(document.referrer)&&this.$(document.location.href)?a=u:(a=e.Q(document.referrer),a=this.T(a||"",document.location.hostname));return a?k.H-k.L>c.vdur?1:4:3},$b:function(){var a,b,e,d,g;k.L=t.getData("Hm_lpvt_"+c.id)||0;13===k.L.length&&(k.L=Math.round(k.L/1E3));b=this.Cb();a=4!==b?1:0;if(e=t.getData("Hm_lvt_"+c.id)){d=e.split(",");for(g=d.length-1;0<=g;g--)13===d[g].length&&(d[g]=""+Math.round(d[g]/1E3));
for(;2592E3<k.H-d[0];)d.shift();g=4>d.length?2:3;for(1===a&&d.push(k.H);4<d.length;)d.shift();e=d.join(",");d=d[d.length-1]}else e=k.H,d="",g=1;t.setData("Hm_lvt_"+c.id,e,c.age);t.setData("Hm_lpvt_"+c.id,k.H);e=l.Qb(this.P(),this.X());if(0===c.nv&&this.$(document.location.href)&&(""===document.referrer||this.$(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=e;this.b.lt=d;this.b.lv=g},Zb:function(){for(var a=[],b=this.b.et,e=+new Date,d=0,g=k.Za.length;d<g;d++){var f=k.Za[d],l=this.b[f];
"undefined"!==typeof l&&""!==l&&("tt"!==f||"tt"===f&&0===b)&&(("ct"!==f||"ct"===f&&0===b)&&("kb"!==f||"kb"===f&&3===b))&&a.push(f+"="+encodeURIComponent(l))}switch(b){case 0:this.b.rt&&a.push("rt="+encodeURIComponent(this.b.rt));break;case 5:a.push("_lpt="+this.F);a.push("_ct="+e);break;case 6:a.push("_lpt="+this.F);a.push("_ct="+e);break;case 90:this.b.rt&&a.push("rt="+this.b.rt)}return a.join("&")},ac:function(){this.$b();this.b.si=c.id;this.b.sn=this.Ma();this.b.su=document.referrer;this.b.hh=
window.location.hash;this.b.ds=g.Vb;this.b.cl=g.colorDepth+"-bit";this.b.ln=String(g.language).toLowerCase();this.b.ja=g.javaEnabled?1:0;this.b.ck=g.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=d.Eb();this.b.v="1.2.64";this.b.cv=decodeURIComponent(t.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=g.Z()+g.R();var a=document.location.href;this.b.cm=e.m(a,k.Ib)||"";this.b.cp=e.m(a,k.Jb)||e.m(a,k.gc)||"";this.b.cw=e.m(a,k.Hb)||e.m(a,k.ic)||"";this.b.ci=e.m(a,
k.Fb)||e.m(a,k.fc)||"";this.b.cf=e.m(a,k.Kb)||e.m(a,k.hc)||"";this.b.cu=e.m(a,k.Gb)||e.m(a,k.ec)||""},init:function(){try{this.ac(),0===this.b.nv?this.Yb():this.Ka(),h.c=this,this.jb(),this.ib(),z.I("pv-b"),this.Wb()}catch(a){var e=[];e.push("si="+c.id);e.push("n="+encodeURIComponent(a.name));e.push("m="+encodeURIComponent(a.message));e.push("r="+encodeURIComponent(document.referrer));b.log(k.xa+"//"+k.Va+"?"+e.join("&"))}},Wb:function(){function a(){z.I("pv-d")}this.Oa?(this.va=u,this.b.et=0,this.b.ep=
"",this.b.p=v(q.A("pageview")),this.b.vl=g.Z()+g.R(),this.i(a),this.b.p=""):a();this.F=+new Date;q.s("pageview")},i:function(a){if(this.Pa){var e=this;e.b.rnd=Math.round(Math.random()*k.ca);z.I("stag-b");var d=k.xa+"//"+k.Va+"?"+e.Zb();z.I("stag-d");e.eb(d);b.log(d,function(b){e.Wa(b);f.d(a,"Function")&&a.call(e)})}},jb:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),d=e.Q(document.referrer)===k.$a?1:0,g=e.m(a,"jn"),f=/^heatlink$|^select$|^pageclick$/.test(g);a&&(b.test(a)&&d&&
f)&&(this.b.rnd=Math.round(Math.random()*k.ca),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",k.protocol+"//"+c.js+g+".js?"+this.b.rnd),g=document.getElementsByTagName("script")[0],g.parentNode.insertBefore(a,g))},ib:function(){if(window.postMessage&&window.self!==window.parent){var a=this;r.e(window,"message",function(b){if(e.Q(b.origin)===k.$a){b=b.data||{};var d=b.jn||"",g=/^customevent$/.test(d);if(RegExp(c.id).test(b.sd||
"")&&g)a.b.rnd=Math.round(Math.random()*k.ca),n(k.protocol+"//"+c.js+d+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}},eb:function(a){var b;try{b=p.parse(m.get("Hm_unsent_"+c.id)||"[]")}catch(e){b=[]}var d=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+d);m.set("Hm_unsent_"+c.id,p.stringify(b))},Wa:function(a){var b;try{b=p.parse(m.get("Hm_unsent_"+c.id)||"[]")}catch(e){b=[]}if(b.length){a=
a.replace(/^https?:\/\//,"");for(var d=0;d<b.length;d++)if(a.replace(/&u=[^&]*/,"")===b[d].replace(/&u=[^&]*/,"")){b.splice(d,1);break}b.length?m.set("Hm_unsent_"+c.id,p.stringify(b)):this.Ka()}},Ka:function(){m.remove("Hm_unsent_"+c.id)},Yb:function(){var a=this,d;try{d=p.parse(m.get("Hm_unsent_"+c.id)||"[]")}catch(e){d=[]}if(d.length)for(var g=function(d){b.log(k.xa+"//"+d,function(b){a.Wa(b)})},f=0;f<d.length;f++)g(d[f])},Ma:function(){return Math.round(+new Date/1E3)%65535}};return new a})();
var B=h.o,C=h.load;if(c.apps){var D=[B.protocol,"//ers.baidu.com/app/s.js?"];D.push(c.apps);C(D.join(""))}(function(){var a=mt.event,e=mt.lang,b=h.o;if(c.kbtrk&&"undefined"!==typeof h.c){h.c.b.kb=e.wa(h.c.b.kb)?h.c.b.kb:0;var d=function(){h.c.b.et=85;h.c.b.ep=h.c.b.kb;h.c.i()};a.e(document,"keyup",function(){h.c.b.kb++});a.e(window,"unload",function(){d()});setInterval(d,b.Rb)}})();var E=h.o,F=h.load;c.pt&&F([E.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
var H=h.o,I=h.load;c.lxb&&I([H.protocol,"//lxbjs.baidu.com/lxb.js?sid=",c.lxb].join(""));var J=h.load,K=h.o.protocol;if(c.qiao){for(var L=[K+"//goutong.baidu.com/site/"],M=c.id,N=5381,O=M.length,P=0;P<O;P++)N=(33*N+Number(M.charCodeAt(P)))%4294967296;2147483648<N&&(N-=2147483648);L.push(N%1E3+"/");L.push(c.id+"/b.js");L.push("?siteId="+c.qiao);J(L.join(""))}
(function(){var a=mt.h,e=mt.lang,b=mt.event,d=mt.r;if("undefined"!==typeof h.c&&(c.med||(!a.Qa||7<a.xb())&&c.cvcc)){var f,l,g,m,p=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},r=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===x)return x},t=function(a,b){var k={};k.n=f;k.t="clk";k.v=a;if(b){var l=b.getAttribute("href"),m=b.getAttribute("onclick")?""+b.getAttribute("onclick"):w,p=b.getAttribute("id")||"";g.test(l)?(k.sn=
"mediate",k.snv=l):e.d(m,"String")&&g.test(m)&&(k.sn="wrap",k.snv=m);k.id=p}h.c.b.et=86;h.c.b.ep=d.stringify(k);h.c.i();for(k=+new Date;400>=+new Date-k;);};if(c.med)l="/zoosnet",f="swt",g=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,m={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f=0,k=b.length;f<k;f++)d=b[f],e=
d.getAttribute("onclick"),d=d.getAttribute("href"),(g.test(e)||g.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){l="/other-comm";f="other";g=c.cvcc.q||s;var q=c.cvcc.id||s;m={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f,k=0,l=b.length;k<l;k++)d=b[k],g!==s?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),q?(d=d.getAttribute("id"),(g.test(e)||
g.test(f)||q.test(d))&&a.push(b[k])):(g.test(e)||g.test(f))&&a.push(b[k])):q!==s&&(d=d.getAttribute("id"),q.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof m&&"undefined"!==typeof g){var v;l+=/\/$/.test(l)?"":"/";var k=function(a,b){if(v===b)return t(l+a,b),x;if(e.d(b,"Array")||e.d(b,"NodeList"))for(var d=0,f=b.length;d<f;d++)if(v===b[d])return t(l+a+"/"+(d+1),b[d]),x};b.e(document,"mousedown",function(a){a=a||window.event;v=a.target||a.srcElement;var b={};for(r(m,function(a,d){b[a]=e.d(d,
"Function")?d():document.getElementById(d)});v&&v!==document&&r(b,k)!==x;)v=v.parentNode})}}})();(function(){var a=mt.f,e=mt.lang,b=mt.event,d=mt.r;if("undefined"!==typeof h.c&&e.d(c.cvcf,"Array")&&0<c.cvcf.length){var f={bb:function(){for(var d=c.cvcf.length,e,m=0;m<d;m++)(e=a.pa(decodeURIComponent(c.cvcf[m])))&&b.e(e,"click",f.oa())},oa:function(){return function(){h.c.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.c.b.ep=d.stringify(a);h.c.i()}}};a.Ba(function(){f.bb()})}})();
(function(){var a=mt.event,e=mt.r;if(c.med&&"undefined"!==typeof h.c){var b={n:"anti",sb:0,kb:0,clk:0},d=function(){h.c.b.et=86;h.c.b.ep=e.stringify(b);h.c.i()};a.e(document,"click",function(){b.clk++});a.e(document,"keyup",function(){b.kb=1});a.e(window,"scroll",function(){b.sb++});a.e(window,"load",function(){setTimeout(d,5E3)})}})();c.spa!==s&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]));})();
